name: img_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/saravanakumar007/image_picker
issue_tracker: https://github.com/saravanakumar007/image_picker/issues
version: 1.0.1

publish_to: 'https://pub.dev/packages/img_picker'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: img_picker_android
      ios:
        default_package: img_picker_ios

dependencies:
  flutter:
    sdk: flutter
  img_picker_android: ^1.0.1
  img_picker_ios: ^1.0.1
  img_picker_platform_interface: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.10
  cross_file: ^0.3.1+1 # Mockito generates a direct include.
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  plugin_platform_interface: ^2.0.0

topics:
  - camera
  - image-picker
  - files
  - file-selection
